name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or the Node version you're using

      # For each microservice 
      - name: Install dependencies for user-service
        working-directory: ./user-service  # Adjust this path based on your structure
        run: npm install

      - name: Run tests for user-service
        working-directory: ./user-service
        run: npm test


      - name: Install dependencies for product-service
        working-directory: ./product-service
        run: npm install

      - name: Run tests for product-service
        working-directory: ./product-service
        run: npm test


      - name: Install dependencies for order-service
        working-directory: ./order-service
        run: npm install

      - name: Run tests for product-service
        working-directory: ./product-service
        run: npm test

        

      # Add deployment steps after tests pass (like Heroku or any other platform)
